### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by maisun** [CarlAmbroselli/homebridge-hue-labs#2]
Hi,

First I'd like to thank you for the plugin, exposing lab functions are very useful for me. However I can't seem to get it work, I received the following error when I start HomeBridge. I tried to uninstall, clean cached accessories without luck. Any idea what's wrong?

(node:32204) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2f536f6b-8294-445b-8e8a-1cf3f82b2efa
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:593:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:382:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:340:10)
    at HueLabsHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-hue-labs-switch/src/platform.ts:104:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by patrickschaper** [comment]
Looks like the plugin wants to expose the  lights the Labs routines will use but they are already exposed by another plugin, e.g. "Homebridge Hue".
Do I understand this right?
